### ISSUE TITLE
Inconsistent Version

### ISSUE THREAD

**Issue by jimbo8098** [GibbonEdu/module-meetTheTeacher#8]
The version output by the API isn't consistent with the version of the module found in the version.php file.

**Comment by rossdotparker** [comment]
Hi Jim, thanks for flagging this. I've fixed this in the commit below, which I'm about to release as v1.1.08:

https://github.com/GibbonEdu/module-meetTheTeacher/commit/9de04d943823c337a9301be3f6970706a20867a4

I wonder if it makes sense to store the version number as a setting, if it always the same as the module version?

**Comment by jimbo8098** [comment]
Hi Ross,

Thanks for taking a look!

Imo should always be the current version so the one I believe is set when
the module updates.

**Comment by rossdotparker** [comment]
All right, that's good to keep in mind for future revisions. Feel free to have at it if you have time, otherwise Ill keep it mind for next time I work on the module.
